# Generated by Django 5.1.4 on 2025-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_duration_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, help_text='Full HTML content for this course', null=True),
        ),
    ]
