# Generated by Django 5.1.4 on 2025-06-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_question_course_quiz_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
