# Generated by Django 5.1.4 on 2025-07-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_quiz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quizzes', to='courses.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'course')},
            },
        ),
    ]
