# Generated by Django 5.1.4 on 2025-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_completedquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
