# Generated by Django 5.2.5 on 2025-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
