# Generated by Django 5.2.5 on 2025-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_playerprofile_current_streak_and_more'),
    ]

    operations = [
        # Add indexes for better query performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_course_title ON courses_course (title);",
            reverse_sql="DROP INDEX IF EXISTS idx_course_title;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_course_level ON courses_course (level);",
            reverse_sql="DROP INDEX IF EXISTS idx_course_level;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_course_category ON courses_course (category);",
            reverse_sql="DROP INDEX IF EXISTS idx_course_category;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_completedquiz_player_course ON courses_completedquiz (player_id, course_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_completedquiz_player_course;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_leaderboard_score ON courses_leaderboardentry (score DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_leaderboard_score;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_purchase_player ON courses_purchase (player_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_purchase_player;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_question_quiz ON courses_question (quiz_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_question_quiz;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_option_question ON courses_option (question_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_option_question;"
        ),
    ]
