# Generated by Django 5.2.5 on 2025-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
