# Generated by Django 5.2.5 on 2025-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='experience_festival_until',
            field=models.DateTimeField(blank=True, help_text='Experience festival active until', null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='fired_up_streak_until',
            field=models.DateTimeField(blank=True, help_text='Fired up streak active until', null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='streak_freeze_count',
            field=models.IntegerField(default=0, help_text='Number of streak freeze items'),
        ),
    ]
